name: Vitest CI

on:
  push:
    branches: [ src ]
  pull_request:
    branches: [ src ]

jobs:
  vitest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Run Vitest tests
      run: npm run test:no-watch
